In [1]:
import os
import logging
import dotenv
import pandas as pd

In [10]:
csv_file = os.path.join("../data/raw", "Luca-null-1505311046242-OneOCR_RC2.csv")
df = pd.read_csv(csv_file)


df["receipt_id"] = "temp"
display(df)

,Unnamed: 0,linetext,linebbox,text,boundingBox,x1,y1,x2,y2,x3,y3,x4,y4,receipt_id
0,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,883,208,884,temp
1,1,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",dal,"[643, 771, 790, 770, 786, 882, 640, 883]",643,771,790,770,786,882,640,883,temp
2,2,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",$ig.,"[783, 770, 971, 771, 967, 880, 779, 882]",783,770,971,771,967,880,779,882,temp
3,3,TAX,"[948, 211, 1859, 196, 1862, 346, 950, 360]",TAX,"[1024, 212, 1701, 205, 1705, 345, 1027, 356]",1024,212,1701,205,1705,345,1027,356,temp
4,4,Data,"[220, 591, 417, 600, 417, 666, 222, 667]",Data,"[240, 592, 420, 600, 417, 675, 237, 667]",240,592,420,600,417,675,237,667,temp
5,5,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]","sono,","[191, 1935, 346, 1934, 348, 1987, 193, 1987]",191,1935,346,1934,348,1987,193,1987,temp
6,6,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",essa,"[353, 1933, 477, 1932, 479, 1987, 355, 1987]",353,1933,477,1932,479,1987,355,1987,temp
7,7,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",quindi,"[491, 1932, 670, 1931, 672, 1987, 493, 1987]",491,1932,670,1931,672,1987,493,1987,temp
8,8,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",e,"[670, 1931, 704, 1930, 706, 1986, 672, 1987]",670,1931,704,1930,706,1986,672,1987,temp
9,9,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",da,"[728, 1930, 783, 1929, 785, 1986, 730, 1986]",728,1930,783,1929,785,1986,730,1986,temp
10,10,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",aggiungersi,"[797, 1929, 1131, 1925, 1133, 1984, 799, 1986]",797,1929,1131,1925,1133,1984,799,1986,temp
11,11,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",in,"[1124, 1925, 1176, 1925, 1178, 1983, 1126, 1984]",1124,1925,1176,1925,1178,1983,1126,1984,temp
12,12,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",base,"[1193, 1925, 1328, 1923, 1330, 1982, 1195, 1983]",1193,1925,1328,1923,1330,1982,1195,1983,temp
13,13,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",alla,"[1338, 1923, 1438, 1921, 1440, 1980, 1340, 1982]",1338,1923,1438,1921,1440,1980,1340,1982,temp
14,14,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",legge,"[1445, 1921, 1600, 1919, 1602, 1978, 1447, 1980]",1445,1921,1600,1919,1602,1978,1447,1980,temp
15,15,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",(Art.,"[1607, 1919, 1748, 1916, 1750, 1976, 1608, 1978]",1607,1919,1748,1916,1750,1976,1608,1978,temp
16,16,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",10,"[1755, 1916, 1820, 1915, 1822, 1975, 1757, 1976]",1755,1916,1820,1915,1822,1975,1757,1976,temp
17,17,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",punto,"[1831, 1915, 1992, 1912, 1994, 1972, 1832, 1975]",1831,1915,1992,1912,1994,1972,1832,1975,temp
18,18,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",14,"[2006, 1912, 2072, 1910, 2073, 1971, 2008, 1972]",2006,1912,2072,1910,2073,1971,2008,1972,temp
19,19,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",D.P.R.,"[2089, 1910, 2258, 1907, 2259, 1967, 2091, 1970]",2089,1910,2258,1907,2259,1967,2091,1970,temp
20,20,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",633,"[2261, 1907, 2364, 1905, 2366, 1965, 2263, 1967]",2261,1907,2364,1905,2366,1965,2263,1967,temp
21,21,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",del,"[2388, 1904, 2475, 1902, 2476, 1962, 2390, 1964]",2388,1904,2475,1902,2476,1962,2390,1964,temp
22,22,"sono, essa quindi e da aggiungersi in base all...","[179, 1931, 2743, 1895, 2744, 1960, 180, 1996]",26/10/72),"[2478, 1902, 2736, 1897, 2738, 1956, 2480, 1962]",2478,1902,2736,1897,2738,1956,2480,1962,temp
23,23,"(Esente I,V.A. - Art. 10 Punto Comma 9 del D.P...","[530, 1742, 2372, 1718, 2373, 1784, 531, 1808]",(Esente,"[523, 1743, 749, 1741, 752, 1806, 527, 1809]",523,1743,749,1741,752,1806,527,1809,temp
24,24,"(Esente I,V.A. - Art. 10 Punto Comma 9 del D.P...","[530, 1742, 2372, 1718, 2373, 1784, 531, 1808]","I,V.A.","[744, 1741, 909, 1739, 911, 1803, 747, 1806]",744,1741,909,1739,911,1803,747,1806,temp
25,25,"(Esente I,V.A. - Art. 10 Punto Comma 9 del D.P...","[530, 1742, 2372, 1718, 2373, 1784, 531, 1808]",-,"[896, 1739, 939, 1738, 942, 1803, 898, 1803]",896,1739,939,1738,942,1803,898,1803,temp
26,26,"(Esente I,V.A. - Art. 10 Punto Comma 9 del D.P...","[530, 1742, 2372, 1718, 2373, 1784, 531, 1808]",Art.,"[939, 1738, 1056, 1737, 1058, 1801, 942, 1803]",939,1738,1056,1737,1058,1801,942,1803,temp
27,27,"(Esente I,V.A. - Art. 10 Punto Comma 9 del D.P...","[530, 1742, 2372, 1718, 2373, 1784, 531, 1808]",10,"[1056, 1737, 1130, 1736, 1132, 1800, 1058, 1801]",1056,1737,1130,1736,1132,1800,1058,1801,temp
28,28,"(Esente I,V.A. - Art. 10 Punto Comma 9 del D.P...","[530, 1742, 2372, 1718, 2373, 1784, 531, 1808]",Punto,"[1130, 1736, 1299, 1734, 1300, 1797, 1132, 1800]",1130,1736,1299,1734,1300,1797,1132,1800,temp
29,29,"(Esente I,V.A. - Art. 10 Punto Comma 9 del D.P...","[530, 1742, 2372, 1718, 2373, 1784, 531, 1808]",Comma,"[1312, 1734, 1516, 1731, 1516, 1794, 1313, 1797]",1312,1734,1516,1731,1516,1794,1313,1797,temp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36,36,Yeusas,"[658, 855, 1269, 877, 1257, 1113, 644, 1118]",Yeusas,"[653, 854, 1304, 877, 1294, 1141, 644, 1118]",653,854,1304,877,1294,1141,644,1118,temp
37,37,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",Si,"[127, 1870, 190, 1870, 190, 1924, 126, 1924]",127,1870,190,1870,190,1924,126,1924,temp
38,38,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",ricorda,"[187, 1870, 384, 1868, 383, 1923, 186, 1924]",187,1870,384,1868,383,1923,186,1924,temp
39,39,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",che,"[398, 1868, 497, 1867, 496, 1923, 398, 1923]",398,1868,497,1867,496,1923,398,1923,temp
40,40,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",il,"[500, 1867, 553, 1866, 553, 1922, 500, 1923]",500,1867,553,1866,553,1922,500,1923,temp
41,41,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",prezzo,"[549, 1866, 736, 1864, 736, 1921, 549, 1922]",549,1866,736,1864,736,1921,549,1922,temp
42,42,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",NON,"[743, 1864, 866, 1863, 866, 1920, 743, 1921]",743,1864,866,1863,866,1920,743,1921,temp
43,43,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",e,"[891, 1862, 926, 1862, 926, 1919, 891, 1920]",891,1862,926,1862,926,1919,891,1920,temp
44,44,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",incluso,"[930, 1862, 1134, 1860, 1134, 1917, 929, 1919]",930,1862,1134,1860,1134,1917,929,1919,temp
45,45,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",di,"[1155, 1859, 1204, 1859, 1204, 1917, 1155, 1917]",1155,1859,1204,1859,1204,1917,1155,1917,temp
46,46,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]","I.V.A.,","[1201, 1859, 1377, 1857, 1377, 1915, 1201, 1917]",1201,1859,1377,1857,1377,1915,1201,1917,temp
47,47,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",mentre,"[1373, 1857, 1574, 1854, 1574, 1912, 1373, 1915]",1373,1857,1574,1854,1574,1912,1373,1915,temp
48,48,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",i,"[1577, 1854, 1613, 1854, 1613, 1912, 1577, 1912]",1577,1854,1613,1854,1613,1912,1577,1912,temp
49,49,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",servizi,"[1609, 1854, 1803, 1852, 1803, 1909, 1609, 1912]",1609,1854,1803,1852,1803,1909,1609,1912,temp
50,50,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",di,"[1813, 1851, 1866, 1851, 1866, 1908, 1813, 1909]",1813,1851,1866,1851,1866,1908,1813,1909,temp
51,51,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",percorrenza,"[1866, 1851, 2204, 1846, 2204, 1902, 1866, 1908]",1866,1851,2204,1846,2204,1902,1866,1908,temp
52,52,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",superiore,"[2218, 1846, 2489, 1843, 2490, 1897, 2218, 1902]",2218,1846,2489,1843,2490,1897,2218,1902,temp
53,53,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",ai,"[2500, 1842, 2563, 1842, 2564, 1895, 2500, 1896]",2500,1842,2563,1842,2564,1895,2500,1896,temp
54,54,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",50,"[2563, 1842, 2637, 1841, 2638, 1894, 2564, 1895]",2563,1842,2637,1841,2638,1894,2564,1895,temp
55,55,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",Km,"[2644, 1840, 2718, 1839, 2719, 1892, 2645, 1893]",2644,1840,2718,1839,2719,1892,2645,1893,temp
56,56,Si ricorda che il prezzo NON e incluso di I.V....,"[118, 1870, 2804, 1837, 2805, 1896, 119, 1929]",lo,"[2746, 1839, 2806, 1838, 2807, 1890, 2747, 1891]",2746,1839,2806,1838,2807,1890,2747,1891,temp
57,57,22.3.2.5.12,"[543, 447, 1714, 482, 1709, 676, 537, 640]",22.3.2.5.12,"[591, 460, 1702, 482, 1712, 680, 592, 643]",591,460,1702,482,1712,680,592,643,temp
58,58,IMPORTO PAGATO E,"[162, 1582, 1082, 1570, 1084, 1658, 164, 1670]",IMPORTO,"[164, 1589, 593, 1578, 594, 1667, 164, 1668]",164,1589,593,1578,594,1667,164,1668,temp
59,59,IMPORTO PAGATO E,"[162, 1582, 1082, 1570, 1084, 1658, 164, 1670]",PAGATO,"[619, 1577, 986, 1574, 989, 1661, 620, 1667]",619,1577,986,1574,989,1661,620,1667,temp
60,60,IMPORTO PAGATO E,"[162, 1582, 1082, 1570, 1084, 1658, 164, 1670]",E,"[1017, 1574, 1069, 1574, 1072, 1660, 1020, 1661]",1017,1574,1069,1574,1072,1660,1020,1661,temp
61,61,Ricevuta Provvisoria di Pagamento,"[531, 378, 2335, 336, 2337, 422, 533, 463]",Ricevuta,"[547, 379, 981, 378, 983, 452, 548, 451]",547,379,981,378,983,452,548,451,temp
62,62,Ricevuta Provvisoria di Pagamento,"[531, 378, 2335, 336, 2337, 422, 533, 463]",Provvisoria,"[1029, 377, 1596, 367, 1599, 441, 1030, 452]",1029,377,1596,367,1599,441,1030,452,temp
63,63,Ricevuta Provvisoria di Pagamento,"[531, 378, 2335, 336, 2337, 422, 533, 463]",di,"[1663, 365, 1744, 362, 1747, 436, 1666, 439]",1663,365,1744,362,1747,436,1666,439,temp
64,64,Ricevuta Provvisoria di Pagamento,"[531, 378, 2335, 336, 2337, 422, 533, 463]",Pagamento,"[1773, 362, 2335, 339, 2338, 408, 1775, 435]",1773,362,2335,339,2338,408,1775,435,temp
65,65,Percorso,"[196, 969, 598, 965, 599, 1069, 198, 1074]",Percorso,"[206, 971, 608, 965, 608, 1072, 205, 1075]",206,971,608,965,608,1072,205,1075,temp

In [3]:
df_max = df.groupby("receipt_id")["receipt_id", "y1", "y2", "x2", "x3"].transform(max).set_index('receipt_id')
df_max["heighest_point"] = df_max[["y1", "y2"]].max(axis=1)
df_max["rightmost_point"] = df_max[["x2", "x3"]].max(axis=1)
df_max = df_max.drop(["y1", "y2", "x2", "x3"], axis=1)
display(df_max.head())

            heighest_point  rightmost_point
receipt_id
temp                  1935             2807
temp                  1935             2807
temp                  1935             2807
temp                  1935             2807
temp                  1935             2807

In [4]:
df_min = df.groupby("receipt_id")["receipt_id", "y3", "y4", "x1", "x4"].transform(min).set_index('receipt_id')
df_min['lowest_point'] = df_min[["y3", "y4"]].max(axis=1)
df_min['leftmost_point'] = df_min[["x1", "x4"]].max(axis=1)
df_min = df_min.drop(["y3", "y4", "x1", "x4"], axis=1)
display(df_min.head())

            lowest_point  leftmost_point
receipt_id
temp                 356             127
temp                 356             127
temp                 356             127
temp                 356             127
temp                 356             127

In [5]:
# Join the dataframes
df = df.set_index('receipt_id')\
    .join(df_max)\
    .join(df_min)
    
display(df.head())

,Unnamed: 0,linetext,linebbox,text,boundingBox,x1,y1,x2,y2,x3,y3,x4,y4,heighest_point,rightmost_point,lowest_point,leftmost_point
receipt_id,,,,,,,,,,,,,,,,,
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,883,208,884,1935,2807,356,127
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,883,208,884,1935,2807,356,127
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,883,208,884,1935,2807,356,127
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,883,208,884,1935,2807,356,127
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,883,208,884,1935,2807,356,127

In [7]:
df["x1_rel"] = (df["x1"] - df["leftmost_point"]) / (df["rightmost_point"] - df["leftmost_point"])
df["y1_rel"] = (df["y1"] - df["lowest_point"]) / (df["heighest_point"] - df["lowest_point"])

df["x2_rel"] = (df["x2"] - df["leftmost_point"]) / (df["rightmost_point"] - df["leftmost_point"])
df["y2_rel"] = (df["y2"] - df["lowest_point"]) / (df["heighest_point"] - df["lowest_point"])

df["x3_rel"] = (df["x3"] - df["leftmost_point"]) / (df["rightmost_point"] - df["leftmost_point"])
df["y3_rel"] = (df["y3"] - df["lowest_point"]) / (df["heighest_point"] - df["lowest_point"])

df["x4_rel"] = (df["x4"] - df["leftmost_point"]) / (df["rightmost_point"] - df["leftmost_point"])
df["y4_rel"] = (df["y4"] - df["lowest_point"]) / (df["heighest_point"] - df["lowest_point"])


display(df.head())

,Unnamed: 0,linetext,linebbox,text,boundingBox,x1,y1,x2,y2,x3,...,lowest_point,leftmost_point,x1_rel,y1_rel,x2_rel,y2_rel,x3_rel,y3_rel,x4_rel,y4_rel
receipt_id,,,,,,,,,,,,,,,,,,,,,
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,...,356,127,0.031343,0.267258,0.184701,0.262825,0.183582,0.333756,0.030224,0.334389
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,...,356,127,0.031343,0.267258,0.184701,0.262825,0.183582,0.333756,0.030224,0.334389
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,...,356,127,0.031343,0.267258,0.184701,0.262825,0.183582,0.333756,0.030224,0.334389
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,...,356,127,0.031343,0.267258,0.184701,0.262825,0.183582,0.333756,0.030224,0.334389
temp,0,Richiesta dal $ig.,"[207, 774, 944, 767, 945, 877, 208, 884]",Richiesta,"[211, 778, 622, 771, 619, 883, 208, 884]",211,778,622,771,619,...,356,127,0.031343,0.267258,0.184701,0.262825,0.183582,0.333756,0.030224,0.334389